# Stubs for thinc.tests.test_util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..neural.ops import CupyOps, NumpyOps
from ..neural.util import get_ops

def test_get_ops() -> None: ...
