# Stubs for thinc.tests.util (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..neural._classes.affine import Affine
from typing import Any

def get_model(W_b_input: Any, cls: Any = ...): ...
def get_shape(W_b_input: Any): ...
