# Stubs for thinc.tests.linear.test_linear (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...linear.linear import LinearModel
from ...neural.ops import NumpyOps
from ...neural.optimizers import SGD
from ...neural.util import to_categorical
from typing import Any

def instances(): ...
def sgd(): ...
def test_basic(instances: Any, sgd: Any) -> None: ...
