# Stubs for torch.optim (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .adadelta import Adadelta
from .adagrad import Adagrad
from .adam import Adam
from .adamax import Adamax
from .asgd import ASGD
from .lbfgs import LBFGS
from .optimizer import Optimizer
from .rmsprop import RMSprop
from .rprop import Rprop
from .sgd import SGD
from .sparse_adam import SparseAdam
