# Stubs for torch.optim.lbfgs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .optimizer import Optimizer
from typing import Any, Optional

class LBFGS(Optimizer):
    def __init__(self, params: Any, lr: int = ..., max_iter: int = ..., max_eval: Optional[Any] = ..., tolerance_grad: float = ..., tolerance_change: float = ..., history_size: int = ..., line_search_fn: Optional[Any] = ...) -> None: ...
    def step(self, closure: Any): ...
