# Stubs for torch.optim.rmsprop (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .optimizer import Optimizer
from typing import Any, Optional

class RMSprop(Optimizer):
    def __init__(self, params: Any, lr: float = ..., alpha: float = ..., eps: float = ..., weight_decay: int = ..., momentum: int = ..., centered: bool = ...) -> None: ...
    def step(self, closure: Optional[Any] = ...): ...
