# Stubs for torch.onnx.operators (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def shape_as_tensor(x: Any): ...
def reshape_from_tensor_shape(x: Any, shape: Any): ...
