# Stubs for torch.multiprocessing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from multiprocessing import *
from .pool import Pool as Pool
from .queue import Queue as Queue, SimpleQueue as SimpleQueue
from typing import Any

def set_sharing_strategy(new_strategy: Any) -> None: ...
def get_sharing_strategy(): ...
def get_all_sharing_strategies(): ...

# Names in __all__ with no definition:
#   Array
#   AuthenticationError
#   Barrier
#   BoundedSemaphore
#   BufferTooShort
#   Condition
#   Event
#   JoinableQueue
#   Lock
#   Manager
#   Pipe
#   Process
#   ProcessError
#   RLock
#   RawArray
#   RawValue
#   Semaphore
#   TimeoutError
#   Value
#   active_children
#   allow_connection_pickling
#   cpu_count
#   current_process
#   freeze_support
#   get_all_start_methods
#   get_context
#   get_logger
#   get_start_method
#   log_to_stderr
#   reducer
#   set_executable
#   set_forkserver_preload
#   set_start_method
