# Stubs for thinc.tests.integration.test_pickle (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...api import with_flatten
from ...v2v import Affine
from typing import Any

def affine(): ...
def test_pickle_with_flatten(affine: Any) -> None: ...
