# Stubs for thinc.tests.integration.test_shape_check (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...exceptions import ShapeMismatchError
from ...neural._classes.affine import Affine

def test_mismatched_shapes_raise_ShapeMismatchError() -> None: ...
