# Stubs for thinc.tests.integration.test_roundtrip_bytes (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...api import chain
from ...neural._classes.maxout import Maxout

def test_simple_model_roundtrip_bytes() -> None: ...
def test_multi_model_roundtrip_bytes() -> None: ...
def test_multi_model_load_missing_dims() -> None: ...
