# Stubs for torch.nn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .modules import *
from .parallel import DataParallel
from .parameter import Parameter
