# Stubs for torch.nn._qscheme (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .._jit_internal import weak_script

def get_enum(qscheme: str) -> int: ...
