# Stubs for torch.nn._reduction (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .._jit_internal import weak_script
from typing import Optional

def get_enum(reduction: str) -> int: ...
def legacy_get_string(size_average: Optional[bool], reduce: Optional[bool], emit_warning: bool=...) -> str: ...
def legacy_get_enum(size_average: Optional[bool], reduce: Optional[bool], emit_warning: bool=...) -> int: ...
