# Stubs for torch.nn.parameter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import torch
from typing import Any, Optional

class Parameter(torch.Tensor):
    def __new__(cls, data: Optional[Any] = ..., requires_grad: bool = ...): ...
    def __deepcopy__(self, memo: Any): ...
    def __reduce_ex__(self, proto: Any): ...
