# Stubs for thinc.neural._classes.elu (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .affine import Affine
from typing import Any

class ELU(Affine):
    def predict(self, input__bi: Any): ...
    def begin_update(self, input__bi: Any, drop: float = ...): ...
