# Stubs for thinc.neural._classes.feature_extracter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .model import Model
from typing import Any

class FeatureExtracter(Model):
    attrs: Any = ...
    def __init__(self, attrs: Any) -> None: ...
    def begin_update(self, docs: Any, drop: float = ...): ...
