# Stubs for thinc.neural._classes.relu (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...check import has_shape
from .affine import Affine
from typing import Any

class ReLu(Affine):
    def predict(self, input__BI: Any): ...
    def begin_update(self, input__BI: Any, drop: float = ...): ...
