# Stubs for thinc.neural._classes.softmax (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...check import has_shape
from ...describe import Synapses
from .affine import Affine
from typing import Any

class Softmax(Affine):
    name: str = ...
    def predict(self, input__BI: Any): ...
    def begin_update(self, input__BI: Any, drop: float = ...): ...
