# Stubs for thinc.extra.wrapt (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .decorators import AdapterFactory, adapter_factory, decorator, synchronized
from .importer import discover_post_import_hooks, notify_module_loaded, register_post_import_hook, when_imported
from .wrappers import BoundFunctionWrapper, CallableObjectProxy, FunctionWrapper, ObjectProxy, PartialCallableObjectProxy, WeakFunctionProxy, apply_patch, function_wrapper, patch_function_wrapper, resolve_path, transient_function_wrapper, wrap_function_wrapper, wrap_object, wrap_object_attribute
from typing import Any

__version_info__: Any
