# Stubs for torch.jit._logging (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

add_stat_value: Any
set_logger: Any
LockingLogger: Any
AggregationType: Any
NoopLogger: Any
time_point: Any
