# Stubs for torch.jit._pickle (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def build_intlist(data: Any): ...
def build_tensor_from_id(data: Any): ...
