# Stubs for torch.autograd.variable (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class VariableMeta(type):
    def __instancecheck__(cls, other: Any): ...

class Variable: ...
