# Stubs for torch.utils.data._utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

IS_WINDOWS: Any

class ExceptionWrapper:
    exc_type: Any = ...
    exc_msg: Any = ...
    def __init__(self, exc_info: Any) -> None: ...

MP_STATUS_CHECK_INTERVAL: float
python_exit_status: bool
