# Stubs for torch.utils.data._utils.collate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

np_str_obj_array_pattern: Any
error_msg_fmt: str
numpy_type_map: Any

def default_collate(batch: Any): ...
