# Stubs for torch._six (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import __builtin__ as builtins
import collections.abc
import io
from typing import Any

PY2: Any
PY3: Any
inf: Any
nan: Any
string_classes = basestring
int_classes: Any
int_classes = int
FileNotFoundError = IOError
FileNotFoundError = builtins.FileNotFoundError

def with_metaclass(meta: Any, *bases: Any): ...

imap: Any
imap = map
exec_: Any

def raise_from(value: Any, from_value: Any) -> None: ...
container_abcs = collections
container_abcs = collections.abc

def get_function_from_type(cls, name: Any): ...
StringIO = io.StringIO

def istuple(obj: Any): ...
