# Stubs for torch._storage_docs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

storage_classes: Any

def add_docstr_all(method: Any, docstr: Any) -> None: ...
