# Stubs for torch._tensor_docs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._torch_docs import parse_kwargs
from typing import Any

def add_docstr_all(method: Any, docstr: Any) -> None: ...

new_common_args: Any
