# Stubs for torch._torch_docs (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def parse_kwargs(desc: Any): ...
def merge_dicts(*dicts: Any): ...

reduceops_common_args: Any
multi_dim_common: Any
single_dim_common: Any
factory_common_args: Any
factory_like_common_args: Any
factory_data_common_args: Any
