# Stubs for thinc.extra.load_nlp (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

SPACY_MODELS: Any
VECTORS: Any

def get_spacy(lang: Any, **kwargs: Any): ...
def register_vectors(ops: Any, lang: Any, data: Any) -> None: ...
def get_vectors(ops: Any, lang: Any): ...
