# Stubs for thinc.extra.visualizer (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def visualize_attention(x: Any, y: Any, weights: Any, layer: str = ..., self_attn: bool = ...) -> None: ...
