# Stubs for thinc.about (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

__name__: str
__summary__: str
__uri__: str
__email__: str
__license__: str
__title__: str
__release__: bool
