# Stubs for thinc.compat (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

basestring = basestring
basestring = str
is_python2: Any
is_python3: Any
is_python_pre_3_5: Any
integer_types: Any
string_types: Any
