# Stubs for thinc.i2v (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .neural._classes.embed import Embed
from .neural._classes.hash_embed import HashEmbed
from .neural._classes.static_vectors import StaticVectors
