# Stubs for thinc.loss (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def categorical_crossentropy(scores: Any, labels: Any): ...
def L1_distance(vec1: Any, vec2: Any, labels: Any, margin: float = ...): ...
