# Stubs for thinc.t2t (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .neural._classes.attention import ParametricAttention
from .neural._classes.convolution import ExtractWindow
from .neural._classes.multiheaded_attention import MultiHeadedAttention, prepare_self_attention
from .neural._classes.rnn import BiLSTM, LSTM

