# Stubs for torch.nn._functions.thnn.auto_symbolic (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def reflectionpad_symbolic(g: Any, input: Any, *params: Any): ...
def replicationpad_symbolic(g: Any, input: Any, *params: Any): ...

symbolic_fns: Any
