# Stubs for torch.nn._functions.thnn.auto (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .auto_double_backwards import double_backwards_fns
from .auto_symbolic import symbolic_fns
