# Stubs for torch.nn._functions.thnn.sparse (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from torch.autograd.function import Function
from typing import Any

MODE_SUM: int
MODE_MEAN: int

class EmbeddingBag(Function):
    @classmethod
    def forward(cls, ctx: Any, weight: Any, indices: Any, offsets: Any, max_norm: Any, norm_type: Any, scale_grad_by_freq: Any, mode: Any): ...
    @staticmethod
    def backward(ctx: Any, grad_output: Any): ...
