# Stubs for torch.distributions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .transforms import *
from .bernoulli import Bernoulli as Bernoulli
from .beta import Beta as Beta
from .binomial import Binomial as Binomial
from .categorical import Categorical as Categorical
from .cauchy import Cauchy as Cauchy
from .chi2 import Chi2 as Chi2
from .constraint_registry import biject_to as biject_to, transform_to as transform_to
from .dirichlet import Dirichlet as Dirichlet
from .distribution import Distribution as Distribution
from .exp_family import ExponentialFamily as ExponentialFamily
from .exponential import Exponential as Exponential
from .fishersnedecor import FisherSnedecor as FisherSnedecor
from .gamma import Gamma as Gamma
from .geometric import Geometric as Geometric
from .gumbel import Gumbel as Gumbel
from .half_cauchy import HalfCauchy as HalfCauchy
from .half_normal import HalfNormal as HalfNormal
from .independent import Independent as Independent
from .kl import kl_divergence as kl_divergence, register_kl as register_kl
from .laplace import Laplace as Laplace
from .log_normal import LogNormal as LogNormal
from .logistic_normal import LogisticNormal as LogisticNormal
from .lowrank_multivariate_normal import LowRankMultivariateNormal as LowRankMultivariateNormal
from .multinomial import Multinomial as Multinomial
from .multivariate_normal import MultivariateNormal as MultivariateNormal
from .negative_binomial import NegativeBinomial as NegativeBinomial
from .normal import Normal as Normal
from .one_hot_categorical import OneHotCategorical as OneHotCategorical
from .pareto import Pareto as Pareto
from .poisson import Poisson as Poisson
from .relaxed_bernoulli import RelaxedBernoulli as RelaxedBernoulli
from .relaxed_categorical import RelaxedOneHotCategorical as RelaxedOneHotCategorical
from .studentT import StudentT as StudentT
from .transformed_distribution import TransformedDistribution as TransformedDistribution
from .uniform import Uniform as Uniform
from .weibull import Weibull as Weibull

# Names in __all__ with no definition:
#   AbsTransform
#   AffineTransform
#   ComposeTransform
#   ExpTransform
#   LowerCholeskyTransform
#   PowerTransform
#   SigmoidTransform
#   SoftmaxTransform
#   StickBreakingTransform
#   Transform
#   identity_transform
