# Stubs for torch.distributions.exp_family (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from torch.distributions.distribution import Distribution

class ExponentialFamily(Distribution):
    def entropy(self): ...
