# Stubs for thinc.extra._vendorized.keras_data_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...compat import HTTPError, URLError, urlopen, urlretrieve
from .keras_generic_utils import Progbar
from typing import Any, Optional

def urlretrieve(url: Any, filename: Any, reporthook: Optional[Any] = ..., data: Optional[Any] = ...) -> None: ...
def get_file(fname: Any, origin: Any, untar: bool = ..., unzip: bool = ..., md5_hash: Optional[Any] = ..., cache_subdir: str = ...): ...
def validate_file(fpath: Any, md5_hash: Any): ...
