# Stubs for torch.nn.utils.convert_parameters (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def parameters_to_vector(parameters: Any): ...
def vector_to_parameters(vec: Any, parameters: Any) -> None: ...
