# Stubs for torch.testing (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

rand_like: Any
randn_like: Any

def assert_allclose(actual: Any, expected: Any, rtol: Optional[Any] = ..., atol: Optional[Any] = ..., equal_nan: bool = ...): ...
def make_non_contiguous(tensor: Any): ...
