# Stubs for torch.nn.backends.thnn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .backend import FunctionBackend
from typing import Any

class THNNFunctionBackend(FunctionBackend):
    def __reduce__(self): ...
    def __deepcopy__(self, memo: Any): ...
    def __copy__(self): ...

backend: Any
