# Stubs for torch.nn._functions.vision (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..._jit_internal import weak_script

def affine_grid_generator(theta: Tensor, size: List[int]) -> Tensor: ...
