# Stubs for torch.distributed (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .distributed_c10d import *
from .distributed_c10d import _backend

def is_available(): ...
