# Stubs for torch.distributed.rendezvous (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def register_rendezvous_handler(scheme: Any, handler: Any) -> None: ...
def rendezvous(url: Any, **kwargs: Any): ...
