# Stubs for torch.nn.parallel.deprecated (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .distributed import DistributedDataParallel as DistributedDataParallel
from .distributed_cpu import DistributedDataParallelCPU as DistributedDataParallelCPU
