# Stubs for thinc.tests.unit.test_pickle (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...linear.linear import LinearModel

def test_pickle_linear_model() -> None: ...
