# Stubs for thinc.tests.unit.test_feature_extracter (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...neural._classes.feature_extracter import FeatureExtracter

def test_pickle() -> None: ...
