# Stubs for thinc.tests.unit.test_pooling (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...neural.vecs2vec import Pooling, max_pool, mean_pool
from typing import Any

def model(request: Any): ...
def X(nB: Any, nI: Any): ...
def dY(X: Any, nI: Any): ...
