# Stubs for thinc.tests.unit.test_beam_search (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...extra.search import MaxViolation

def test_init_violn() -> None: ...
