# Stubs for thinc.tests.unit.test_hash_embed (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...neural._classes.hash_embed import HashEmbed

def test_init() -> None: ...
def test_seed_changes_bucket() -> None: ...
