# Stubs for spacy.tokens (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .doc import Doc as Doc
from .span import Span as Span
from .token import Token as Token
