# Stubs for thinc.neural._lsuv (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .util import copy_array
from typing import Any, Optional

def svd_orthonormal(shape: Any): ...
def do_lsuv(ops: Any, weights: Any, predict: Any, X: Any): ...
def LSUVinit(model: Any, X: Any, y: Optional[Any] = ...): ...
