# Stubs for thinc.neural.vecs2vec (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..api import layerize
from typing import Any

def Pooling(*funcs: Any, **kwargs: Any): ...
def mean_pool(X_lengths: Any, drop: float = ...): ...
def max_pool(X_lengths: Any, drop: float = ...): ...
