# Stubs for pytorch_transformers.convert_tf_checkpoint_to_pytorch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def convert_tf_checkpoint_to_pytorch(tf_checkpoint_path: Any, bert_config_file: Any, pytorch_dump_path: Any) -> None: ...
