# Stubs for pytorch_transformers.convert_gpt2_checkpoint_to_pytorch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def convert_gpt2_checkpoint_to_pytorch(gpt2_checkpoint_path: Any, gpt2_config_file: Any, pytorch_dump_folder_path: Any) -> None: ...
