# Stubs for pytorch_transformers.convert_xlnet_checkpoint_to_pytorch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

GLUE_TASKS_NUM_LABELS: Any

def convert_xlnet_checkpoint_to_pytorch(tf_checkpoint_path: Any, bert_config_file: Any, pytorch_dump_folder_path: Any, finetuning_task: Optional[Any] = ...) -> None: ...
