# Stubs for pytorch_transformers.convert_xlm_checkpoint_to_pytorch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def convert_xlm_checkpoint_to_pytorch(xlm_checkpoint_path: Any, pytorch_dump_folder_path: Any) -> None: ...
