# Stubs for pytorch_transformers.convert_openai_checkpoint_to_pytorch (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def convert_openai_checkpoint_to_pytorch(openai_checkpoint_folder_path: Any, openai_config_file: Any, pytorch_dump_folder_path: Any) -> None: ...
