# Stubs for torch.nn.parallel._functions (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from torch.autograd import Function
from typing import Any

class Broadcast(Function):
    @staticmethod
    def forward(ctx: Any, target_gpus: Any, *inputs: Any): ...
    @staticmethod
    def backward(ctx: Any, *grad_outputs: Any): ...

class ReduceAddCoalesced(Function):
    @staticmethod
    def forward(ctx: Any, destination: Any, num_inputs: Any, *grads: Any): ...
    @staticmethod
    def backward(ctx: Any, *grad_outputs: Any): ...

class Gather(Function):
    @staticmethod
    def forward(ctx: Any, target_device: Any, dim: Any, *inputs: Any): ...
    @staticmethod
    def backward(ctx: Any, grad_output: Any): ...

class Scatter(Function):
    @staticmethod
    def forward(ctx: Any, target_gpus: Any, chunk_sizes: Any, dim: Any, input: Any): ...
    @staticmethod
    def backward(ctx: Any, *grad_output: Any): ...
