# Stubs for torch.nn.parallel.parallel_apply (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def get_a_var(obj: Any): ...
def parallel_apply(modules: Any, inputs: Any, kwargs_tup: Optional[Any] = ..., devices: Optional[Any] = ...): ...
