# Stubs for torch.nn.parallel.replicate (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def replicate(network: Any, devices: Any, detach: bool = ...): ...
