# Stubs for torch.nn.parallel.scatter_gather (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._functions import Gather, Scatter
from typing import Any

def scatter(inputs: Any, target_gpus: Any, dim: int = ...): ...
def scatter_kwargs(inputs: Any, kwargs: Any, target_gpus: Any, dim: int = ...): ...
def gather(outputs: Any, target_device: Any, dim: int = ...): ...
